"""Add price discount to flight

Revision ID: 6ccac8fe059f
Revises: 33e5db2050bf
Create Date: 2019-02-10 13:59:45.629996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccac8fe059f'
down_revision = '33e5db2050bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('cabin_class_code', sa.String(length=1), nullable=True, comment='舱位级别代码：Y:经济舱；C:公务舱；F:头等舱'))
    op.add_column('flights', sa.Column('cancellation_fee', sa.Integer(), nullable=True, comment='退票费'))
    op.add_column('flights', sa.Column('changing_seat_fee', sa.Integer(), nullable=True, comment='改舱费'))
    op.add_column('flights', sa.Column('lowest_price_discount', sa.Float(), nullable=True, comment='最低价格折扣'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'lowest_price_discount')
    op.drop_column('flights', 'changing_seat_fee')
    op.drop_column('flights', 'cancellation_fee')
    op.drop_column('flights', 'cabin_class_code')
    # ### end Alembic commands ###
